app:
  name: horaperfeita
spring:
  application:
    name: horaperfeita
  datasource:
    url: jdbc:postgresql://localhost:5432/horaperfeita
    username: horaperfeita_user
    password: horaperfeita_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  docker:
    compose:
      file: ./run/postgres-dev.yml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger
api:
  security:
    token:
      secret: secret-token-api