app:
  name: horaperfeita
spring:
  application:
    name: horaperfeita
  datasource:
    url: jdbc:mysql://mysql:3310/horaperfeita
    username: horaperfeita
    password: horaperfeita
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  docker:
    compose:
      file: ./run/docker-compose.yml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger
api:
  security:
    token:
      secret: secret-token-api
