version: '3.9'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3310:3306/tcp
    expose:
      - 3310
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horaperfeita
      MYSQL_USER: horaperfeita
      MYSQL_PASSWORD: horaperfeita
  horaperfeita_app:
    image: horaperfeita:dev
    container_name: horaperfeita_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/horaperfeita
      SPRING_DATASOURCE_USERNAME: horaperfeita
      SPRING_DATASOURCE_PASSWORD: horaperfeita
    ports:
      - "9901:8080"
    depends_on:
      - mysql
    networks:
      - horaperfeita_network
volumes:
  mysql_data:

networks:
  horaperfeita_network:
